package com.scholarops.model.enums;

public enum PermissionType {
    USER_MANAGE,
    ROLE_ASSIGN,
    AUDIT_VIEW,
    PASSWORD_ADMIN_RESET,
    CRAWL_SOURCE_MANAGE,
    CRAWL_RULE_MANAGE,
    CRAWL_RUN_MANAGE,
    CONTENT_REVIEW,
    CONTENT_VIEW,
    QUESTION_BANK_MANAGE,
    QUIZ_MANAGE,
    QUIZ_TAKE,
    SUBMISSION_VIEW_OWN,
    SUBMISSION_VIEW_ALL,
    GRADING_MANAGE,
    GRADING_VIEW,
    SCHEDULE_MANAGE_OWN,
    PLAGIARISM_VIEW,
    WRONG_ANSWER_VIEW_OWN
}
